server:
  port: 8010
spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/product
      username: product
      password: product
      driver-class-name: com.mysql.cj.jdbc.Driver
      max-active: 12
      max-wait: 1000
      max-wait-thread-count: 10000
mybatis:
  mapper-locations: classpath:mbg/mapper/**.xml
  type-aliases-package: person.search.alltool.pojo





